language: node_js
node_js:
  - 14
cache:
  directories:
  - node_modules
script:
  - npm install && npm run build
  - npm run test
after_failure: cat /home/travis/.npm/_logs/*-debug.log
warnings_are_errors: false
env:
  CI=false
# Look into cloning and deploying the playground directly. For now,
# we won't deploy.
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $github_token
#  local_dir: build
#  on:
#    branch: master
